Fix call into Pillow using deprecated tostring.
Traceback (most recent call last):
  File "r2/lib/nymph.py", line 185, in <module>
    print spritify(sys.argv[1], sys.argv[2])
  File "r2/lib/nymph.py", line 178, in spritify
    images = _load_spritable_images(css_filename)
  File "r2/lib/nymph.py", line 94, in _load_spritable_images
    image_hash = hashlib.md5(image.convert("RGBA").tostring()).hexdigest()
  File "/usr/local/lib/python2.7/dist-packages/Pillow-3.1.0.rc1-py2.7-linux-x86_64.egg/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.
make: *** [build/public/static/reddit.css] Error 1